// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxo48_tTFgVXfiOEFRlCfu7SGMPPjIEKM',
    appId: '1:615088349750:web:b9063dd7505f07d16bee97',
    messagingSenderId: '615088349750',
    projectId: 'login-vet-app',
    authDomain: 'login-vet-app.firebaseapp.com',
    databaseURL: 'https://login-vet-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-vet-app.appspot.com',
    measurementId: 'G-KECP34D4NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJj1rM6LjIEF4A58clGnghEJ-OPBKU1o',
    appId: '1:615088349750:android:2b5dec59a0ad30766bee97',
    messagingSenderId: '615088349750',
    projectId: 'login-vet-app',
    databaseURL: 'https://login-vet-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-vet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQfGQjsUeVKR10UOtnK3OfQBfBIUvWnXs',
    appId: '1:615088349750:ios:067924c738a3d7c36bee97',
    messagingSenderId: '615088349750',
    projectId: 'login-vet-app',
    databaseURL: 'https://login-vet-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-vet-app.appspot.com',
    iosBundleId: 'com.example.vetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQfGQjsUeVKR10UOtnK3OfQBfBIUvWnXs',
    appId: '1:615088349750:ios:1d8a16e3d3933ff06bee97',
    messagingSenderId: '615088349750',
    projectId: 'login-vet-app',
    databaseURL: 'https://login-vet-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-vet-app.appspot.com',
    iosBundleId: 'com.example.vetApp.RunnerTests',
  );
}
